config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: "oauth/tokens"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  require "sidekiq/web"
  require "sidekiq_unique_jobs/web"

  authenticated :user, ->(user) { user.tech_admin? } do
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
    Sidekiq::Web.set :sessions, Rails.application.config.session_options
    Sidekiq::Web.class_eval do
      use Rack::Protection, origin_whitelist: [URL.url] # resolve Rack Protection HttpOrigin
    end
    mount Sidekiq::Web => "/sidekiq"
    mount FieldTest::Engine, at: "abtests"
  end

  namespace :resource_admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  namespace :internal do
    get "/", to: redirect("/internal/articles")

    authenticate :user, ->(user) { user.has_role?(:tech_admin) } do
      mount Blazer::Engine, at: "blazer"

      flipper_ui = Flipper::UI.app(Flipper,
                                   { rack_protection: { except: %i[authenticity_token form_token json_csrf
                                                                   remote_token http_origin session_hijacking] } })
      mount flipper_ui, at: "feature_flags"
    end

    resources :articles, only: %i[index show update]
    resources :broadcasts
    resources :buffer_updates, only: %i[create update]
    resources :listings, only: %i[index edit update destroy]
    resources :comments, only: [:index]
    resources :events, only: %i[index create update]
    resources :feedback_messages, only: %i[index show]
    resources :invitations, only: %i[index new create]
    resources :pages, only: %i[index new create edit update destroy]
    resources :mods, only: %i[index update]
    resources :moderator_actions, only: %i[index]
    resources :privileged_reactions, only: %i[index]
    resources :permissions, only: %i[index]
    resources :podcasts, only: %i[index edit update destroy] do
      member do
        post :fetch
        post :add_admin
        delete :remove_admin
      end
    end
    resources :reactions, only: [:update]
    resources :response_templates, only: %i[index new edit create update destroy]
    resources :chat_channels, only: %i[index create update] do
      member do
        delete :remove_user
      end
    end
    resources :reports, only: %i[index show], controller: "feedback_messages" do
      collection do
        post "send_email"
        post "create_note"
        post "save_status"
      end
    end
    resources :tags, only: %i[index update show]
    resources :users, only: %i[index show edit update] do
      member do
        post "banish"
        post "full_delete"
        patch "user_status"
        post "merge"
        delete "remove_identity"
        post "recover_identity"
        post "send_email"
        post "verify_email_ownership"
        patch "unlock_access"
      end
    end
    resources :organization_memberships, only: %i[update destroy create]
    resources :organizations, only: %i[index show] do
      member do
        patch "update_org_credits"
      end
    end
    resources :sponsorships, only: %i[index edit update destroy]
    resources :welcome, only: %i[index create]
    resources :growth, only: %i[index]
    resources :tools, only: %i[index create] do
      collection do
        post "bust_cache"
      end
    end
    resources :webhook_endpoints, only: :index
    resource :config
    resources :badges, only: :index
    post "badges/award_badges", to: "badges#award_badges"
    resources :secrets, only: %i[index]
    put "secrets", to: "secrets#update"
  end

  namespace :stories, defaults: { format: "json" } do
    resource :feed, only: [:show] do
      get ":timeframe" => "feeds#show"
    end
  end

  namespace :api, defaults: { format: "json" } do
    scope module: :v0,
          constraints: ApiConstraints.new(version: 0, default: true) do
      resources :articles, only: %i[index show create update] do
        collection do
          get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
          get "/:username/:slug", to: "articles#show_by_slug", as: :slug
        end
      end
      resources :comments, only: %i[index show]
      resources :videos, only: [:index]
      resources :podcast_episodes, only: [:index]
      resources :users, only: %i[show] do
        collection do
          get :me
        end
      end
      resources :tags, only: [:index]
      resources :follows, only: [:create]
      namespace :followers do
        get :users
        get :organizations
      end
      resources :webhooks, only: %i[index create show destroy]

      resources :listings, only: %i[index show create update]
      get "/listings/category/:category", to: "listings#index", as: :listings_category
      get "/analytics/totals", to: "analytics#totals"
      get "/analytics/historical", to: "analytics#historical"
      get "/analytics/past_day", to: "analytics#past_day"
      get "/analytics/referrers", to: "analytics#referrers"

      resources :health_checks, only: [] do
        collection do
          get :app
          get :search
          get :database
          get :cache
        end
      end
    end
  end

  namespace :notifications do
    resources :counts, only: [:index]
    resources :reads, only: [:create]
  end

  namespace :incoming_webhooks do
    get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
    post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
  end

  resources :messages, only: [:create]
  resources :chat_channels, only: %i[index show create update]
  resources :chat_channel_memberships, only: %i[index create edit update destroy]
  resources :articles, only: %i[update create destroy]
  resources :article_mutes, only: %i[update]
  resources :comments, only: %i[create update destroy] do
    patch "/hide", to: "comments#hide"
    patch "/unhide", to: "comments#unhide"
    collection do
      post "/moderator_create", to: "comments#moderator_create"
    end
  end
  resources :comment_mutes, only: %i[update]
  resources :users, only: %i[index], defaults: { format: :json } # internal API
  resources :users, only: %i[update] do
    resource :twitch_stream_updates, only: %i[show create]
  end
  resources :twitch_live_streams, only: :show, param: :username
  resources :reactions, only: %i[index create]
  resources :response_templates, only: %i[index create edit update destroy]
  resources :feedback_messages, only: %i[index create]
  resources :organizations, only: %i[update create destroy]
  resources :followed_articles, only: [:index]
  resources :follows, only: %i[show create update] do
    collection do
      get "/bulk_show", to: "follows#bulk_show"
    end
  end
  resources :image_uploads, only: [:create]
  resources :notifications, only: [:index]
  resources :tags, only: [:index] do
    collection do
      get "/onboarding", to: "tags#onboarding"
    end
  end
  resources :stripe_active_cards, only: %i[create update destroy]
  resources :github_repos, only: %i[index] do
    collection do
      post "/update_or_create", to: "github_repos#update_or_create"
    end
  end
  resources :buffered_articles, only: [:index]
  resources :events, only: %i[index show]
  resources :videos, only: %i[index create new]
  resources :video_states, only: [:create]
  resources :twilio_tokens, only: [:show]
  resources :html_variants, only: %i[index new create show edit update]
  resources :html_variant_trials, only: [:create]
  resources :html_variant_successes, only: [:create]
  resources :tag_adjustments, only: %i[create destroy]
  resources :rating_votes, only: [:create]
  resources :page_views, only: %i[create update]
  resources :listings, only: %i[index new create edit update destroy dashboard]
  resources :credits, only: %i[index new create] do
    get "purchase", on: :collection, to: "credits#new"
  end
  resources :buffer_updates, only: [:create]
  resources :reading_list_items, only: [:update]
  resources :poll_votes, only: %i[show create]
  resources :poll_skips, only: [:create]
  resources :profile_pins, only: %i[create update]
  resources :partnerships, only: %i[index create show], param: :option
  resources :display_ad_events, only: [:create]
  resources :badges, only: [:index]
  resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
  resources :podcasts, only: %i[new create]
  resources :article_approvals, only: %i[create]
  resources :video_chats, only: %i[show]
  resources :user_subscriptions, only: %i[create] do
    collection do
      get "/subscribed", action: "subscribed"
    end
  end
  namespace :followings, defaults: { format: :json } do
    get :users
    get :tags
    get :organizations
    get :podcasts
  end

  resource :onboarding, only: :show

  get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
  get "/search/tags" => "search#tags"
  get "/search/chat_channels" => "search#chat_channels"
  get "/search/listings" => "search#listings"
  get "/search/users" => "search#users"
  get "/search/feed_content" => "search#feed_content"
  get "/search/reactions" => "search#reactions"
  get "/chat_channel_memberships/find_by_chat_channel_id" => "chat_channel_memberships#find_by_chat_channel_id"
  get "/listings/dashboard" => "listings#dashboard"
  get "/listings/:category" => "listings#index", :as => :listing_category
  get "/listings/:category/:slug" => "listings#index", :as => :listing_slug

app/controllers/internal/application_controller.rb
module Internal
  class ApplicationController < ApplicationController
    before_action :authorize_admin
    after_action :verify_authorized

    # This is used in app/views/internal/shared/_navbar.html.erb to build the
    # side navbar in alphabetical order.
    MENU_ITEMS = [
      { name: "articles",           controller: "articles" },
      { name: "broadcasts",         controller: "broadcasts" },
      { name: "badges",             controller: "badges" },
      { name: "chat_channels",      controller: "chat_channels" },
      { name: "comments",           controller: "comments" },
      { name: "config",             controller: "config" },
      { name: "events",             controller: "events" },
      { name: "growth",             controller: "growth" },
      { name: "listings",           controller: "listings" },
      { name: "moderator_actions",  controller: "moderator_actions" },
      { name: "mods",               controller: "mods" },
      { name: "privileged_reactions", controller: "privileged_reactions" },
      { name: "organizations",      controller: "organizations" },
      { name: "pages",              controller: "pages" },
      { name: "permissions",        controller: "permissions" },
      { name: "podcasts",           controller: "podcasts" },
      { name: "reports",            controller: "reports" },
      { name: "response_templates", controller: "response_templates" },
      { name: "sponsorships",       controller: "sponsorships" },
      { name: "tags",               controller: "tags" },
      { name: "tools",              controller: "tools" },
      { name: "users",              controller: "users" },
      { name: "vault secrets",      controller: "secrets" },
      { name: "webhooks",           controller: "webhook_endpoints" },
      { name: "welcome",            controller: "welcome" },
    ].sort_by { |menu_item| menu_item[:name] }.freeze

    private

    def authorization_resource
      self.class.name.demodulize.sub("Controller", "").singularize.constantize
    end

    def authorize_admin
      authorize(authorization_resource, :access?, policy_class: InternalPolicy)
    end
  end
end

app/controllers/internal/articles_controller.rb
module Internal
  class ArticlesController < Internal::ApplicationController
    layout "internal"

    after_action only: [:update] do
      Audit::Logger.log(:moderator, current_user, params.dup)
    end

    def index
      @pending_buffer_updates = BufferUpdate.where(status: "pending").includes(:article)
      @user_buffer_updates = BufferUpdate.where(status: "sent_direct", approver_user_id: current_user.id).where(
        "created_at > ?", 24.hours.ago
      )

      case params[:state]
      when /not-buffered/
        days_ago = params[:state].split("-")[2].to_f
        @articles = articles_not_buffered(days_ago)
      when /top-/
        months_ago = params[:state].split("-")[1].to_i.months.ago
        @articles = articles_top(months_ago)
      when "satellite"
        @articles = articles_satellite
      when "satellite-not-bufffered"
        @articles = articles_satellite.where(last_buffered: nil)
      when "boosted-additional-articles"
        @articles = articles_boosted_additional
      when "chronological"
        @articles = articles_chronological
      else
        @articles = articles_mixed
        @featured_articles = articles_featured
      end
    end

    def show
      @article = Article.find(params[:id])
    end

    def update
      article = Article.find(params[:id])
      article.featured = article_params[:featured].to_s == "true"
      article.approved = article_params[:approved].to_s == "true"
      article.email_digest_eligible = article_params[:email_digest_eligible].to_s == "true"
      article.boosted_additional_articles = article_params[:boosted_additional_articles].to_s == "true"
      article.boosted_dev_digest_email = article_params[:boosted_dev_digest_email].to_s == "true"
      article.user_id = article_params[:user_id].to_i
      article.update!(article_params)
      render body: nil
    end

    private

    def articles_not_buffered(days_ago)
      Article.published
        .where(last_buffered: nil)
        .where("published_at > ? OR crossposted_at > ?", days_ago.days.ago, days_ago.days.ago)
        .includes(:user)
        .limited_columns_internal_select
        .order(public_reactions_count: :desc)
        .page(params[:page])
        .per(50)
    end

    def articles_top(months_ago)
      Article.published
        .where("published_at > ?", months_ago)
        .includes(user: [:notes])
        .limited_columns_internal_select
        .order(public_reactions_count: :desc)
        .page(params[:page])
        .per(50)
    end

    def articles_satellite
      Article.published.where(last_buffered: nil)
        .includes(:user, :buffer_updates)
        .tagged_with(Tag.bufferized_tags, any: true)
        .limited_columns_internal_select
        .order(hotness_score: :desc)
        .page(params[:page])
        .per(60)
    end

    def articles_boosted_additional
      Article.boosted_via_additional_articles
        .includes(:user, :buffer_updates)
        .limited_columns_internal_select
        .order(published_at: :desc)
        .page(params[:page])
        .per(100)
    end

    def articles_chronological
      Article.published
        .includes(user: [:notes])
        .limited_columns_internal_select
        .order(published_at: :desc)
        .page(params[:page])
        .per(50)
    end

    def articles_mixed
      Article.published
        .includes(user: [:notes])
        .limited_columns_internal_select
        .order(hotness_score: :desc)
        .page(params[:page])
        .per(30)
    end

    def articles_featured
      Article.published.or(Article.where(published_from_feed: true))
        .where(featured: true)
        .where("featured_number > ?", Time.current.to_i)
        .includes(:user, :buffer_updates)
        .limited_columns_internal_select
        .order(featured_number: :desc)
    end

    def article_params
      allowed_params = %i[featured
                          social_image
                          body_markdown
                          approved
                          email_digest_eligible
                          boosted_additional_articles
                          boosted_dev_digest_email
                          main_image_background_hex_color
                          featured_number
                          user_id
                          last_buffered]
      params.require(:article).permit(allowed_params)
    end

    def authorize_admin
      authorize Article, :access?, policy_class: InternalPolicy
    end
  end
end

app/controllers/internal/badges_controller.rb
module Internal
  class BadgesController < Internal::ApplicationController
    layout "internal"

    def index
      @badges = Badge.all
    end

    def award_badges
      raise ArgumentError, "Please choose a badge to award" if permitted_params[:badge].blank?

      usernames = permitted_params[:usernames].split(/\s*,\s*/)
      message = permitted_params[:message_markdown].presence || "Congrats!"
      BadgeAchievements::BadgeAwardWorker.perform_async(usernames, permitted_params[:badge], message)

      flash[:success] = "Badges are being rewarded. The task will finish shortly."
      redirect_to internal_badges_url
    rescue ArgumentError => e
      flash[:danger] = e.message
      redirect_to "/internal/badges"
    end

    private

    def permitted_params
      params.permit(:usernames, :badge, :message_markdown)
    end
  end
end

app/controllers/internal/growth_controller.rb
module Internal
  class GrowthController < Internal::ApplicationController
    layout "internal"
  end
end

app/views/internal/podcasts/edit.html.erb
<hr />
<h2 class="m-0 mb-3"><%= link_to @podcast.title, "/#{@podcast.slug}" %></h2>
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header">
        <h3>Fetch episodes</h3>
      </div>
      <div class="card-body">
        <%= form_with(url: fetch_internal_podcast_path(@podcast.id), method: :post, local: true) do %>
          <div class="form-group">
            <%= check_box_tag :force %>
            <%= label_tag :force %>
            <small>(When checked, the existing episodes' urls will be re-checked and episodes reachable and https fields will be updated accordingly if needed.)</small>
          </div>
          <div class="form-group">
            <%= text_field_tag :limit, 5, size: 2 %>
            <%= label_tag :limit %>
            <small>(The number of episodes to fetch. When set to an empty string, last 1_000 episodes will be fetched.)</small>
          </div>
          <%= submit_tag "Fetch episodes", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-header">
        <h3>Manage Admins</h3>
      </div>
      <div class="card-body">
        <% if @podcast.admins.present? %>
          <ul class="list-group list-group-flush mb-3">
            <% @podcast.admins.each do |admin| %>
              <%= form_for @podcast, url: remove_admin_internal_podcast_path(@podcast.id), html: { method: :delete, class: "form-inline" } do |f| %>
                <li class="list-group-item w-100">
                  <%= link_to "@#{admin.username}", "/#{admin.username}" %>
                  <%= f.hidden_field :user_id, value: admin.id %>
                  <%= f.submit "Remove", class: "btn btn-danger btn-sm float-right" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% else %>
          <p>There are no admins for this podcast.</p>
        <% end %>

        <% if @podcast.creator.present? %>
          <p>Created by <%= link_to "@#{@podcast.creator.username}", "/#{@podcast.creator.username}" %></p>
        <% end %>

        <%= form_for @podcast, url: add_admin_internal_podcast_path(@podcast.id), html: { method: :post } do |f| %>
          <div class="form-group">
            <%= f.label "Add Admin (by user_id)", for: "podcast_user_id" %>
            <%= f.text_field :user_id, value: "", class: "form-control" %>
          </div>
          <%= f.submit "Add Admin", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-header">
        <h3>Edit Podcast</h3>
      </div>
      <div class="card-body">
        <%= form_for [:internal, @podcast] do |f| %>
          <hr>
          <div class="form-group">
            <%= f.label :title, for: "podcast_title" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :feed_url, for: "podcast_feed_url" %>
            <%= f.text_field :feed_url, class: "form-control" %>
          </div>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/internal/podcasts/index.html.erb
<div class="row m-3">
  <div class="col">
    <%= form_tag("/internal/podcasts", method: "get") do %>
      <div class="form-row justify-content-end">
        <div class="form-group">
          <%= text_field_tag(:search, params[:search]) %>
          <%= submit_tag("Search") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= paginate @podcasts %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Feed URL</th>
      <th scope="col">Eps</th>
      <th scope="col">Reach</th>
      <th scope="col">Pub</th>
      <th scope="col">Status Notice</th>
      <th scope="col">Admin</th>
    </tr>
  </thead>
  <tbody>
    <% @podcasts.each do |podcast| %>
    <tr>
      <td><%= podcast.id %></td>
      <td><%= link_to podcast.title, edit_internal_podcast_path(podcast) %></td>
      <td><%= link_to podcast.feed_url, podcast.feed_url %></td>
      <td><%= podcast.episodes_count %></td>
      <td><%= podcast.reachable %></td>
      <td><%= podcast.published %></td>
      <td><%= podcast.status_notice %></td>
      <td>
        <% podcast.admins.pluck(:username).each do |username| %>
          <%= link_to "@#{username}", "/#{username}" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @podcasts %>